/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package student.management;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ManageTest {
    @Test
    void getAllStudentsTest() {
        //
    }

    @Test
    void addStudentTest() {
        //
    }

    @Test
    void getStudentByNameTest() {
        //
    }

    @Test
    void removeStudentByIdTest() {
        //
    }

    @Test
    void updateStudentTest() {
        //
    }
}
